#!/bin/bash

main(){
  local namespace="$1"
  local service_base_name="$2"
  local service_suffix="$3"
  local service_prefix="${namespace}-${service_base_name}"

  local register_docker_name="${service_prefix}-register-${service_suffix}"

  docker stop \
    "${register_docker_name}" &> /dev/null
}
main $@
