#!/bin/bash

run(){
  local docker_name="$1"
  local docker_url="$2"
  local memory_limit="$3"
  local port="$4"
  local bind_port="$5"
  local env_file="/tmp/${docker_name}.env"

  docker rm --force "${docker_name}"

  docker run --rm \
    --name "${docker_name}" \
    --env-file "${env_file}" \
    --memory "${memory_limit}" \
    --publish "${bind_port}:${port}" \
    "${docker_url}"
}

tattle(){
  local service_prefix="$1"
  local docker_name="$2"
  local tattle_docker_name="$3"
  local service_docker_url="$4"
  local etcd_dir="$5"
  local exit_code="$6"
  local tattle_docker_url="$(etcdctl get /octoblu/tattle/docker_url)"

  docker run --rm \
    --name "${tattle_docker_name}" \
    --env TATTLE_EXIT_CODE="${exit_code}" \
    --env TATTLE_DOCKER_URL="${service_docker_url}" \
    --env TATTLE_ETCD_DIR="${etcd_dir}" \
    --env-file "/tmp/${tattle_docker_name}.env" \
    "${tattle_docker_url}"
}

main(){
  local service_prefix="$1"
  local service_suffix="$2"
  local memory_limit="$3"
  local docker_url_etcd_key="$4"
  local etcd_dir="$5"
  local port="${6:-80}"
  local bind_port="$7"
  local docker_url="$(etcdctl get ${docker_url_etcd_key})"

  local docker_name="${service_prefix}-${service_suffix}"
  local tattle_docker_name="${service_prefix}-tattle-${service_suffix}"

  run "${docker_name}" "${docker_url}" "${memory_limit}" "${port}" "${bind_port}"
  local exit_code=$?
  if [ "${exit_code}" != "0" ]; then
    echo "Things went pear-shaped, tattling"
    tattle "${service_name}" "${docker_name}" "${tattle_docker_name}" "${docker_url}" "${etcd_dir}" "${exit_code}"
    exit $exit_code
  fi
}
main $@
