#!/bin/bash

main(){
  local service_prefix="$1"
  local service_suffix="$2"

  local service_docker_name="${service_prefix}-${service_suffix}"
  local register_docker_name="${service_prefix}-register-${service_suffix}"

  docker kill \
    --signal=HUP \
    "${register_docker_name}" > /dev/null

  docker stop "${service_docker_name}" &> /dev/null
  exit 0
}
main $@
