#!/bin/bash

extract(){
  local script_path="$1"
  local service_name="$2"
  local destination="/run/kronk/${service_name}/${script_path}"

  mkdir -p "$(dirname $destination)" \
  && etcdctl get "${script_path}" > "${destination}" \
  && chmod +x "${destination}"
}

execute(){
  local script_path="$1"
  local service_name="$2"
  local args="$3"
  local destination="/run/kronk/${service_name}/${script_path}"

  bash -c "${destination} ${args}"
}

main(){
  local script_path="$1"
  shift
  local service_name="$1"
  shift
  local args="$@"

  extract "${script_path}" "${service_name}" \
  && execute "${script_path}" "${service_name}" "${args}"
  exit $?
}
main $@
