#!/bin/bash

assert_docker_url_etcd_key() {
  local docker_url_etcd_key="$1"
  etcdctl get "${docker_url_etcd_key}" 4&> /dev/null
  if [ "$?" != "0" ]; then
    echo "etcd did not contain: ${docker_url_etcd_key}"
    exit 1
  fi
}

docker_login() {
  /usr/bin/docker login \
    --username $(/usr/bin/etcdctl get /docker/quay.io/username 2>/dev/null) \
    --password $(/usr/bin/etcdctl get /docker/quay.io/password 2>/dev/null) \
    --email $(/usr/bin/etcdctl get /docker/quay.io/email 2>/dev/null) \
    quay.io
}

stop_docker_with_force() {
  /usr/bin/docker rm \
    --force \
    $@ &> /dev/null
}

stop_docker() {
  /usr/bin/docker stop \
    $@ &> /dev/null
}

write_env_file() {
  local env_docker_name="$1"
  local docker_name="$2"
  local etcd_key="$3"
  /usr/bin/docker run --rm \
    --name "${env_docker_name}" \
    --env ETCDCTL_PEERS=http://$(ifconfig docker0 | grep 'inet ' | awk '{print $2}'):2379 \
    quay.io/octoblu/etcd-to-env "${etcd_key}" > "/tmp/${docker_name}.env" 2> /dev/null
}

main(){
  local namespace="$1"
  local service_base_name="$2"
  local service_prefix="${namespace}-${service_base_name}"
  local etcd_dir="${namespace}/${service_base_name}"
  local docker_url_etcd_key="${etcd_dir}/docker_url"
  local env_etcd_key="${etcd_dir}/env"
  local register_docker_name="${service_prefix}-register"
  local env_docker_name="${service_prefix}-env"
  local docker_name="${service_prefix}"
  local tattle_docker_name="${service_prefix}-tattle"
  local tattle_env_docker_name="${service_prefix}-tattle-env"

  assert_docker_url_etcd_key "${docker_url_etcd_key}"
  stop_docker_with_force "${env_docker_name}" "${docker_name}" "${tattle_docker_name}" "${tattle_env_docker_name}"
  stop_docker "${register_docker_name}"
  docker_login
  write_env_file "${env_docker_name}" "${docker_name}" "${env_etcd_key}"
  write_env_file "${tattle_env_docker_name}" "${tattle_docker_name}" "/octoblu/tattle/env"
}
main $@
